name: main CI
on:
  push:
    branches:
      - main

jobs:
  linux-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create build dir
      run: mkdir build
    - name: Generate make files
      run: cmake build
    - name: Build
      run: |
        cd build
        make
    - name: Test
      run: |
        cd build
        ctest --output-on-failure
      
  # macos-tests:
  #   runs-on: macos-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2
  #   - name: Run tests
  #     run: cargo test --verbose
      
  # windows-tests:
  #   runs-on: windows-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2
  #   - name: Run tests
  #     run: cargo test --verbose